<?php

return array (
  'ADMIN_PASSWORD' => NULL,
  'ADMIN_USERNAME' => NULL,
  'CONTACT_PASSWORD' => NULL,
  'CONTACT_USERNAME' => NULL,
  'DIRECTOR_PASSWORD' => NULL,
  'DIRECTOR_USERNAME' => NULL,
  'MAILADMIN_PASSWORD' => NULL,
  'MAILSERVER_PASSWORD' => NULL,
  'OWNER_PASSWORD' => NULL,
  'OWNER_USERNAME' => NULL,
  'SYSTEM_PASSWORD' => NULL,
  'SYSTEM_USERNAME' => NULL,
);
