version: '3.5'
services:
  ispmailadmin-api:
    build: ./fpm
    user: "501:20"
    restart: always
    working_dir: /var/www/html
    container_name: ispmailadmin-api
    env_file:
      - ../../.env.local
    volumes:
      - "../../:/var/www/html:delegated"
      - "~/.composer:/home/dockeruser/.composer:cached"
      - "cache_ispmailadmin-api:/var/www/html/var/cache:cached"
      - "log_ispmailadmin-api:/var/www/html/var/log:cached"
      - './xdebug.ini:/usr/local/etc/php/docker-php-ext-xdebug.ini:rw'
    networks:
      - docker-env
    labels:
      - "traefik.frontend.rule=Host:ispmailadmin-api.ii.dev"
      - "traefik.port=8000"
      - "traefik.backend=ispmailadmin-api"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=https"
    environment:
      # See https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
      # See https://github.com/docker/for-linux/issues/264
      # The `remote_host` below may optionally be replaced with `remote_connect_back`
      XDEBUG_CONFIG: >-
        remote_enable=1
        remote_host=host.docker.internal
        remote_port=9001
        idekey=PHPSTORM


volumes:
  cache_ispmailadmin-api:
  log_ispmailadmin-api:

networks:
  docker-env:
    external: true
