version: '3.4'
services:

    # nginx
    co-monolith-web:
        image: youthinking8/co-monolith-web
        working_dir: /var/www/project
        networks:
            - docker-env
            - internal
        environment:
            - APP_ENV=prod
            - APP_DEBUG=0
            - APP_SECRET=c68378c59a1b87abd0a9fa0b389e51df
        deploy:
            replicas: 1
            labels:
                - "traefik.frontend.rule=Host:hangukeo.dev"
                - "traefik.port=80"
                - "traefik.backend=co-monolith-web"
                - "traefik.enable=true"
                - "traefik.frontend.entryPoints=https,http"

    # fpm
    co-monolith-app:
        image: youthinking8/co-monolith-app
        working_dir: /var/www/project
        networks:
            - internal
        environment:
            - APP_ENV=prod
            - APP_DEBUG=0
            - APP_SECRET=c68378c59a1b87abd0a9fa0b389e51df
            - TRUSTED_PROXIES=10.0.0.0/24
        deploy:
            replicas: 1
            labels:
                - "traefik.enable=false"


    redis:
        image: redis:alpine
        deploy:
            replicas: 1
            labels:
                - "traefik.enable=false"
        networks:
            - internal

    postgres-12:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: guest
            POSTGRES_DATABASE: hangukeo
            POSTGRES_PASSWORD: pdQqR%K9hV3b
        networks:
            - internal
        volumes:
            - "co-monolith_db:/var/lib/postgresql:rw"
        deploy:
            labels:
                - "traefik.enable=false"


volumes:
    co-monolith_db:

networks:
    docker-env:
        external: true
    internal:
        external: false