test:
  path: /
  methods: GET
  controller: App\UI\Action\DefaultAction

# Doc
api_doc:
  path: /doc
  methods: GET
  controller: App\UI\Doc\ApiDocController

# auth
get_token:
  path: /login
  methods: POST
  controller: App\UI\Action\CreateTokenAction

#domain
list_domain:
  path: /domain
  methods: GET
  controller: App\UI\Action\ListDomainAction

create_domain:
  path: /domain
  methods: POST
  controller: App\UI\Action\CreateDomainAction

delete_domain:
  path: /domain/{domain}
  methods: DELETE
  controller: App\UI\Action\DeleteDomainAction

# users
list_users:
  path: /users
  methods: GET
  controller: App\UI\Action\ListUserAction

create_user:
  path: /user
  methods: POST
  controller: App\UI\Action\CreateUserAction

get_user:
  path: /user/{email}
  methods: GET
  controller: App\UI\Action\GetUserByEmailAction

update_user:
  path: /user/{email}
  methods: PUT
  controller: App\UI\Action\UpdateUserAction

delete_user:
  path: /user/{email}
  methods: DELETE
  controller: App\UI\Action\DeleteUserAction

patch_user:
  path: /user/{email}
  methods: PATCH
  controller: App\UI\Action\PatchUserAction

# alias
list_alias:
  path: /alias
  methods: GET
  controller: App\UI\Action\ListAliasesAction

create_alias:
  path: /alias
  methods: POST
  controller: App\UI\Action\CreateAliasAction

delete_alias:
  path: /alias/source/{source}/destination/{destination}
  methods: DELETE
  controller: App\UI\Action\DeleteAliasAction